services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka-node
    network_mode: "host"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      KAFKA_NODE_ID: ${NODE_ID}
      CLUSTER_ID: 'Lwd5AsdFS5Sw5_plMxPFhw'
      KAFKA_PROCESS_ROLES: 'broker,controller'

      # Bind to 0.0.0.0 (all interfaces) on the host to guarantee successful binding
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${NODE_IP}:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@10.0.2.11:9093,2@10.0.2.12:9093,3@10.0.2.13:9093'
      
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3                   # default replication factor for topics
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3               # replication factor for the internal offsets topic
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3       # replication factor for the transaction state topic
      KAFKA_MIN_INSYNC_REPLICAS: 2                          # minimum number of replicas that must acknowledge a write for the write to be considered successful
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2                  # minimum number of in-sync replicas for the transaction state topic      

      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
      
      # How often Kafka checks for partition leader imbalance (e.g., 300 seconds / 5 mins)
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: '300'
      
      # Percentage of allowed imbalance per broker before a rebalance kicks off (e.g., 10%)
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: '10'

      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data: