services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka-node
    network_mode: "host"
    restart: always
    environment:
      KAFKA_NODE_ID: ${NODE_ID}
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://${NODE_IP}:9092,EXTERNAL://${NODE_IP}:9094'
      CLUSTER_ID: 'Lwd5AsdFS5Sw5_plMxPFhw'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://10.0.2.11:9092,CONTROLLER://10.0.2.11:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@10.0.2.11:9093,2@10.0.2.12:9093,3@10.0.2.13:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3

      # using /tmp error access denied
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data: